Specify project dependencies in pyproject.toml; delete requirements.txt
g8a9/ferret pull request #32
Opened 2024-01-03 11:18 UTC by cesarc09

Added project dependencies for poetry. The versions are obtained by default by installing ferret with the minimum possible python version (3.7, as setup.py requires python>=3.7). As the required packages are now listed in pyproject.toml, requirements.txt is not needed anymore. 
The installation was done and verified using "SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip install .", "pip install ." gave the pip error that is already known and talked about under "Getting started" on the main page.

2024-01-04 17:20 UTC, g8a9 commented on setup.py
Since we are moving to poetry, we must remove requirements from setup.py, too.
I think you can simply set them to an empty list
```python
requirements = list()
```

2024-01-04 17:20 UTC, g8a9 requested changes
We only need to strip requirements from setup.py and we are good to go with poetry.

2024-01-05 10:17 UTC, cesarc09 commented on setup.py
Done!

2024-01-05 10:25 UTC, cesarc09 commented
A final note: Starting from Python 3.8.1 it gets correctly installed with "pip install ." ( so without SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True) and works with the example in ReadMe.md. 
When testing Python 3.7.6, the following error occurs: 
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

Apparently because protobuf 4.x.x is installed by another dependency. A workaround for this is to run "pip uninstall protobuf" and " pip install protobuf==3.20.3", after which everything works correctly. 
A nicer fix could be to add a protobuf dependency in pyproject.toml and install the correct version depending on the python version, but for this I wanted your insight if it is necessary (also because python 3.7 is quite old at this point).

2024-01-05 16:33 UTC, cesarc09 commented
In the newest commit, python 3.8 is now the minimum version. The package gets correctly installed using "pip install ." and runs the example code with no problem.

2024-01-08 18:22 UTC, g8a9 approved these changes

2024-01-08 18:38 UTC, g8a9 commented
@cesarc09 I've edited the file as it was not supporting python=3.8.0 previously.

2024-01-08 18:57 UTC, merged